drop database BRAWAN; 

CREATE database BRAWAN; 

USE BRAWAN; 

CREATE TABLE IF NOT EXISTS CLIENTE(

ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
RG CHAR(30),
CPF CHAR(30),
SEXO VARCHAR(15),
TELEFONE VARCHAR(80),
EMAIL VARCHAR(150),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
TG_STATUS INT(1),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO(

ID BIGINT NOT NULL AUTO_INCREMENT,
CODIGO VARCHAR(20),
NOME  VARCHAR(100),
QUANTIDADE INTEGER,
CATEGORIA CHAR(15),
MARCA CHAR(15),
TAMANHO CHAR(15),
VL_UNITARIO varchar(10),
DESCRICAO VARCHAR(150),
TG_STATUS INT(1),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS EMPRESA (

ID BIGINT NOT NULL AUTO_INCREMENT,
EMPRESA  VARCHAR(100),
DIRETOR  VARCHAR(100),
CNPJ CHAR(30),
TELEFONE VARCHAR(80),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
EMAIL VARCHAR(150),
TG_STATUS CHAR(1),
PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS FUNCIONARIO (

ID BIGINT NOT NULL AUTO_INCREMENT,
LOGIN VARCHAR(150),
SENHA VARCHAR(150),
NOME  VARCHAR(100),
RG CHAR(30),
CPF CHAR(30),
TELEFONE VARCHAR(80),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
EMAIL VARCHAR(150),
SEXO VARCHAR(15),
CARGO VARCHAR(100),
EMPRESA VARCHAR(60),
FK_EMPRESA BIGINT NOT NULL,
TG_STATUS INT(1),
PRIMARY KEY (ID),
FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA (ID)
);

CREATE TABLE IF NOT EXISTS FI_VENDA (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
FK_CLIENTE BIGINT NOT NULL,
FK_CAIXA BIGINT NOT NULL,
FK_EMPRESA BIGINT NOT NULL,
QUANTIDADE NUMERIC(6),
DT_VENDA DATE NOT NULL,
VL_TOTAL DECIMAL(13,2),
DH_INCLUSAO DATETIME,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_CAIXA) REFERENCES FUNCIONARIO (ID),
FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE (ID).
FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA (ID)
);


CREATE TABLE IF NOT EXISTS ITEMVENDA (

PK_ID BIGINT NOT NULL AUTO_INCREMENT,
FK_PRODUTO BIGINT NOT NULL,
DH_INCLUSAO DATETIME,
SOMA INTEGER,
PRIMARY KEY (PK_ID),
FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO (ID)
);

INSERT INTO CLIENTE
(NOME,RG,CPF,SEXO,TELEFONE,EMAIL,ENDERECO,BAIRRO,CIDADE,UF,CEP,TG_STATUS)
VALUES ('BRUNO BALDARENA','55.369.814-X','479.537.578/00','MASCULINO','11-99791-7090','BRUNOBALDARENA@GMAIL.COM','RUA SANTOS,123','SAO CARLOS','CARAPICUIBA','SP','09972-390',0);

INSERT INTO CLIENTE
(NOME,RG,CPF,SEXO,TELEFONE,EMAIL,ENDERECO,BAIRRO,CIDADE,UF,CEP,TG_STATUS)
VALUES ('CHUNG LUNG TSAI','55.212.814-X','235.139.308/28','MASCULINO','11-98923-3232','CHUNGLUNG@GMAIL.COM','RUA SANTOS,123','SAO CARLOS','CARAPICUIBA','SP','09972-390',0);

INSERT INTO CLIENTE
(NOME,RG,CPF,SEXO,TELEFONE,EMAIL,ENDERECO,BAIRRO,CIDADE,UF,CEP,TG_STATUS)
VALUES ('DEYVID VIEIRA','34.864.229-5','347.494.808/35','MASCULINO','11-99431-7090','DEYVIDVIEIRA@GMAIL.COM','RUA SANTOS,123','SAO CARLOS','CARAPICUIBA','SP','09972-390',0);

INSERT INTO CLIENTE
(NOME,RG,CPF,SEXO,TELEFONE,EMAIL,ENDERECO,BAIRRO,CIDADE,UF,CEP,TG_STATUS)
VALUES ('ANTONIO TORRES','37.485.089-6','391.255.838/83','MASCULINO','11-99712-7090','ANTONIOTORRES@GMAIL.COM','RUA SANTOS,123','SAO CARLOS','CARAPICUIBA','SP','09972-390',0);


INSERT INTO PRODUTO
(CODIGO,NOME,QUANTIDADE,CATEGORIA,MARCA,TAMANHO,VL_UNITARIO,DESCRICAO,TG_STATUS)
VALUES ('1','POLO NIKE BRANCO',10,'CAMISA','NIKE','P','22.00','ISSO É UMA CAMISA POLO BRANCA',0);

INSERT INTO PRODUTO
(CODIGO,NOME,QUANTIDADE,CATEGORIA,MARCA,TAMANHO,VL_UNITARIO,DESCRICAO,TG_STATUS)
VALUES ('2','CALÇA JEANS',10,'Calça','Oakley','m','64.00','ISSO É UMA CALÇA JEANS',0);

INSERT INTO FUNCIONARIO (LOGIN,SENHA,NOME,RG,CPF,TELEFONE,ENDERECO,BAIRRO,CIDADE,UF,CEP,EMAIL,SEXO,CARGO,EMPRESA,FK_EMPRESA,TG_STATUS)
VALUES ('BALDARENA', 'e795f68a39acc352d44c6328f1ffc2a0', 'BRUNO','55.212.814-X','235.139.308/28','11-99431-7090','RUA SANTOS,123','BARUERI','SAO PAULO','SP','BRUNO@GAMIL.COM','MASCULINO','GERENTE','LOJA DE ROUPAS BRAWAM SP','1',0);
